# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vsa-compilation',
                'doc_host': 'https://hanleyc01.github.io',
                'git_url': 'https://github.com/hanleyc01/vsa-compilation',
                'lib_path': 'vsa_compilation'},
  'syms': {'vsa_compilation.core': {'vsa_compilation.core.foo': ('core.html#foo', 'vsa_compilation/core.py')}}}
