# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vsa-compilation',
                'doc_host': 'https://hanleyc01.github.io',
                'git_url': 'https://github.com/hanleyc01/vsa-compilation',
                'lib_path': 'vsa_compilation'},
  'syms': { 'vsa_compilation.vsas': { 'vsa_compilation.vsas.HRR': ('vsas.html#hrr', 'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.HRR.__array_finalize__': ( 'vsas.html#hrr.__array_finalize__',
                                                                                       'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.HRR.__new__': ('vsas.html#hrr.__new__', 'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.HRR.bind': ('vsas.html#hrr.bind', 'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.HRR.cosine_similarity': ( 'vsas.html#hrr.cosine_similarity',
                                                                                      'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.HRR.inverse': ('vsas.html#hrr.inverse', 'vsa_compilation/vsas.py'),
                                      'vsa_compilation.vsas.random': ('vsas.html#random', 'vsa_compilation/vsas.py')}}}
