"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_vsas.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/00_vsas.ipynb 3
def foo(): pass

# %% ../nbs/00_vsas.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f"Hello {to}"
